# This file maps source markdown files to their target wiki pages
# format:
# - source: path/to/markdown/file.md
#   target: Wiki-Page-Name

mappings:
  - source: benchmarks/rotatingDrum/readme.md
    target: Performance-of-phasicFlow
  - source: doc/mdDocs/howToBuild-V1.0.md
    target: How-to-build-PhasicFlow‐v‐1.0
  - source: tutorials/README.md
    target: Tutorials
  # Add more mappings as needed